### ISSUE TITLE
TD 6 & 7 - Exercise 1

### ISSUE THREAD

**Issue by lbeziaud** [Aurele-Barriere/M1_RI#2]
Hi,

It would be great if the answers for the first exercise were available.

Please help me!

**Comment by SemDyal** [comment]
Je n'apporte probablement pas beaucoup d'infos mais il faut s'inspirer de ce qui a été vu en cours. Il faut considérer les attributs In, Ex, Prod et Suppr. Dans la question 2, le parcours des instructions se fait à l'envers, les attributs In et Ex sont donc inversés.
